name: Pull Request CI

on:
  pull_request:
    branches:
      - dev

jobs:
  test_oslg:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run Tests
      run: |
        echo $(pwd)
        echo $(ls)
        docker exec -t test pwd
        docker exec -t test ls
        docker exec -t test bundle update
        docker exec -t test bundle exec rake
        docker kill test
